// source: pando/api/survey/v1/preview.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var pando_api_extensions_pb = require('../../../../pando/api/extensions_pb.js');
goog.object.extend(proto, pando_api_extensions_pb);
var pando_api_shared_pb = require('../../../../pando/api/shared_pb.js');
goog.object.extend(proto, pando_api_shared_pb);
var pando_api_survey_v1_shared_pb = require('../../../../pando/api/survey/v1/shared_pb.js');
goog.object.extend(proto, pando_api_survey_v1_shared_pb);
goog.exportSymbol('proto.pando.api.survey.v1.GetNextQuestionPreviewRequest', null, global);
goog.exportSymbol('proto.pando.api.survey.v1.GetNextQuestionPreviewResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pando.api.survey.v1.GetNextQuestionPreviewRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.displayName = 'proto.pando.api.survey.v1.GetNextQuestionPreviewRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pando.api.survey.v1.GetNextQuestionPreviewResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.displayName = 'proto.pando.api.survey.v1.GetNextQuestionPreviewResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.survey.v1.GetNextQuestionPreviewRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    questionAnswersMap: (f = msg.getQuestionAnswersMap()) ? f.toObject(includeInstance, undefined) : [],
    questionGuid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    surveyVersionGuid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    dataRecord: (f = msg.getDataRecord()) && pando_api_shared_pb.DataRecord.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.survey.v1.GetNextQuestionPreviewRequest}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.survey.v1.GetNextQuestionPreviewRequest;
  return proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.survey.v1.GetNextQuestionPreviewRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.survey.v1.GetNextQuestionPreviewRequest}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getQuestionAnswersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestionGuid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSurveyVersionGuid(value);
      break;
    case 4:
      var value = new pando_api_shared_pb.DataRecord;
      reader.readMessage(value,pando_api_shared_pb.DataRecord.deserializeBinaryFromReader);
      msg.setDataRecord(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.survey.v1.GetNextQuestionPreviewRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuestionAnswersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getQuestionGuid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSurveyVersionGuid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDataRecord();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      pando_api_shared_pb.DataRecord.serializeBinaryToWriter
    );
  }
};


/**
 * map<string, string> question_answers = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.getQuestionAnswersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.pando.api.survey.v1.GetNextQuestionPreviewRequest} returns this
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.clearQuestionAnswersMap = function() {
  this.getQuestionAnswersMap().clear();
  return this;};


/**
 * optional string question_guid = 2;
 * @return {string}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.getQuestionGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.GetNextQuestionPreviewRequest} returns this
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.setQuestionGuid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string survey_version_guid = 3;
 * @return {string}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.getSurveyVersionGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.GetNextQuestionPreviewRequest} returns this
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.setSurveyVersionGuid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional pando.api.DataRecord data_record = 4;
 * @return {?proto.pando.api.DataRecord}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.getDataRecord = function() {
  return /** @type{?proto.pando.api.DataRecord} */ (
    jspb.Message.getWrapperField(this, pando_api_shared_pb.DataRecord, 4));
};


/**
 * @param {?proto.pando.api.DataRecord|undefined} value
 * @return {!proto.pando.api.survey.v1.GetNextQuestionPreviewRequest} returns this
*/
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.setDataRecord = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pando.api.survey.v1.GetNextQuestionPreviewRequest} returns this
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.clearDataRecord = function() {
  return this.setDataRecord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewRequest.prototype.hasDataRecord = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.survey.v1.GetNextQuestionPreviewResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    questionGuid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.survey.v1.GetNextQuestionPreviewResponse}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.survey.v1.GetNextQuestionPreviewResponse;
  return proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.survey.v1.GetNextQuestionPreviewResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.survey.v1.GetNextQuestionPreviewResponse}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestionGuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.survey.v1.GetNextQuestionPreviewResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuestionGuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string question_guid = 1;
 * @return {string}
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.prototype.getQuestionGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.GetNextQuestionPreviewResponse} returns this
 */
proto.pando.api.survey.v1.GetNextQuestionPreviewResponse.prototype.setQuestionGuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.pando.api.survey.v1);
