// source: pando/api/survey/v1/reports.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var pando_api_extensions_pb = require('../../../../pando/api/extensions_pb.js');
goog.object.extend(proto, pando_api_extensions_pb);
var pando_api_shared_pb = require('../../../../pando/api/shared_pb.js');
goog.object.extend(proto, pando_api_shared_pb);
var pando_api_survey_v1_shared_pb = require('../../../../pando/api/survey/v1/shared_pb.js');
goog.object.extend(proto, pando_api_survey_v1_shared_pb);
goog.exportSymbol('proto.pando.api.survey.v1.ChartData', null, global);
goog.exportSymbol('proto.pando.api.survey.v1.GetInstancesReportRequest', null, global);
goog.exportSymbol('proto.pando.api.survey.v1.GetInstancesReportRequest.TargetCase', null, global);
goog.exportSymbol('proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest', null, global);
goog.exportSymbol('proto.pando.api.survey.v1.SurveyInstanceStatus', null, global);
goog.exportSymbol('proto.pando.api.survey.v1.SurveyInstancesStatusList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.survey.v1.GetInstancesReportRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.pando.api.survey.v1.GetInstancesReportRequest.oneofGroups_);
};
goog.inherits(proto.pando.api.survey.v1.GetInstancesReportRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.survey.v1.GetInstancesReportRequest.displayName = 'proto.pando.api.survey.v1.GetInstancesReportRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.displayName = 'proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pando.api.survey.v1.SurveyInstancesStatusList.repeatedFields_, null);
};
goog.inherits(proto.pando.api.survey.v1.SurveyInstancesStatusList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.survey.v1.SurveyInstancesStatusList.displayName = 'proto.pando.api.survey.v1.SurveyInstancesStatusList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.survey.v1.SurveyInstanceStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pando.api.survey.v1.SurveyInstanceStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.survey.v1.SurveyInstanceStatus.displayName = 'proto.pando.api.survey.v1.SurveyInstanceStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.survey.v1.ChartData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pando.api.survey.v1.ChartData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.survey.v1.ChartData.displayName = 'proto.pando.api.survey.v1.ChartData';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.TargetCase = {
  TARGET_NOT_SET: 0,
  USER_ID: 1,
  ORGANIZATION_CODE: 2
};

/**
 * @return {proto.pando.api.survey.v1.GetInstancesReportRequest.TargetCase}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.getTargetCase = function() {
  return /** @type {proto.pando.api.survey.v1.GetInstancesReportRequest.TargetCase} */(jspb.Message.computeOneofCase(this, proto.pando.api.survey.v1.GetInstancesReportRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.survey.v1.GetInstancesReportRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.survey.v1.GetInstancesReportRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    organizationCode: jspb.Message.getFieldWithDefault(msg, 2, ""),
    start: (f = msg.getStart()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    end: (f = msg.getEnd()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    page: jspb.Message.getFieldWithDefault(msg, 100, 0),
    resultsPerPage: jspb.Message.getFieldWithDefault(msg, 101, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.survey.v1.GetInstancesReportRequest;
  return proto.pando.api.survey.v1.GetInstancesReportRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.survey.v1.GetInstancesReportRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrganizationCode(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStart(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEnd(value);
      break;
    case 100:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    case 101:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setResultsPerPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.survey.v1.GetInstancesReportRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.survey.v1.GetInstancesReportRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStart();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEnd();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      100,
      f
    );
  }
  f = message.getResultsPerPage();
  if (f !== 0) {
    writer.writeInt32(
      101,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest} returns this
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.setUserId = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.pando.api.survey.v1.GetInstancesReportRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest} returns this
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.clearUserId = function() {
  return jspb.Message.setOneofField(this, 1, proto.pando.api.survey.v1.GetInstancesReportRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.hasUserId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string organization_code = 2;
 * @return {string}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.getOrganizationCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest} returns this
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.setOrganizationCode = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.pando.api.survey.v1.GetInstancesReportRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest} returns this
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.clearOrganizationCode = function() {
  return jspb.Message.setOneofField(this, 2, proto.pando.api.survey.v1.GetInstancesReportRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.hasOrganizationCode = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp start = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.getStart = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest} returns this
*/
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.setStart = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest} returns this
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.clearStart = function() {
  return this.setStart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.hasStart = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp end = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.getEnd = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest} returns this
*/
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.setEnd = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest} returns this
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.clearEnd = function() {
  return this.setEnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.hasEnd = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 page = 100;
 * @return {number}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 100, 0));
};


/**
 * @param {number} value
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest} returns this
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 100, value);
};


/**
 * optional int32 results_per_page = 101;
 * @return {number}
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.getResultsPerPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 101, 0));
};


/**
 * @param {number} value
 * @return {!proto.pando.api.survey.v1.GetInstancesReportRequest} returns this
 */
proto.pando.api.survey.v1.GetInstancesReportRequest.prototype.setResultsPerPage = function(value) {
  return jspb.Message.setProto3IntField(this, 101, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    organizationCode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    isChartDataIncluded: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    isCompletedOnly: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    page: jspb.Message.getFieldWithDefault(msg, 100, 0),
    resultsPerPage: jspb.Message.getFieldWithDefault(msg, 101, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest}
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest;
  return proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest}
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrganizationCode(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsChartDataIncluded(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsCompletedOnly(value);
      break;
    case 100:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    case 101:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setResultsPerPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrganizationCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIsChartDataIncluded();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getIsCompletedOnly();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      100,
      f
    );
  }
  f = message.getResultsPerPage();
  if (f !== 0) {
    writer.writeInt32(
      101,
      f
    );
  }
};


/**
 * optional string organization_code = 1;
 * @return {string}
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.getOrganizationCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest} returns this
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.setOrganizationCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool is_chart_data_included = 2;
 * @return {boolean}
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.getIsChartDataIncluded = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest} returns this
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.setIsChartDataIncluded = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool is_completed_only = 3;
 * @return {boolean}
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.getIsCompletedOnly = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest} returns this
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.setIsCompletedOnly = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional int32 page = 100;
 * @return {number}
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 100, 0));
};


/**
 * @param {number} value
 * @return {!proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest} returns this
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 100, value);
};


/**
 * optional int32 results_per_page = 101;
 * @return {number}
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.getResultsPerPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 101, 0));
};


/**
 * @param {number} value
 * @return {!proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest} returns this
 */
proto.pando.api.survey.v1.GetSurveyInstanceStatusesRequest.prototype.setResultsPerPage = function(value) {
  return jspb.Message.setProto3IntField(this, 101, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.survey.v1.SurveyInstancesStatusList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.survey.v1.SurveyInstancesStatusList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.toObject = function(includeInstance, msg) {
  var f, obj = {
    surveyInstanceStatusList: jspb.Message.toObjectList(msg.getSurveyInstanceStatusList(),
    proto.pando.api.survey.v1.SurveyInstanceStatus.toObject, includeInstance),
    chartDataList: jspb.Message.toObjectList(msg.getChartDataList(),
    proto.pando.api.survey.v1.ChartData.toObject, includeInstance),
    pagination: (f = msg.getPagination()) && pando_api_shared_pb.PaginationResult.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.survey.v1.SurveyInstancesStatusList}
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.survey.v1.SurveyInstancesStatusList;
  return proto.pando.api.survey.v1.SurveyInstancesStatusList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.survey.v1.SurveyInstancesStatusList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.survey.v1.SurveyInstancesStatusList}
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pando.api.survey.v1.SurveyInstanceStatus;
      reader.readMessage(value,proto.pando.api.survey.v1.SurveyInstanceStatus.deserializeBinaryFromReader);
      msg.addSurveyInstanceStatus(value);
      break;
    case 2:
      var value = new proto.pando.api.survey.v1.ChartData;
      reader.readMessage(value,proto.pando.api.survey.v1.ChartData.deserializeBinaryFromReader);
      msg.addChartData(value);
      break;
    case 100:
      var value = new pando_api_shared_pb.PaginationResult;
      reader.readMessage(value,pando_api_shared_pb.PaginationResult.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.survey.v1.SurveyInstancesStatusList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.survey.v1.SurveyInstancesStatusList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSurveyInstanceStatusList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.pando.api.survey.v1.SurveyInstanceStatus.serializeBinaryToWriter
    );
  }
  f = message.getChartDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.pando.api.survey.v1.ChartData.serializeBinaryToWriter
    );
  }
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      pando_api_shared_pb.PaginationResult.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SurveyInstanceStatus survey_instance_status = 1;
 * @return {!Array<!proto.pando.api.survey.v1.SurveyInstanceStatus>}
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.getSurveyInstanceStatusList = function() {
  return /** @type{!Array<!proto.pando.api.survey.v1.SurveyInstanceStatus>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pando.api.survey.v1.SurveyInstanceStatus, 1));
};


/**
 * @param {!Array<!proto.pando.api.survey.v1.SurveyInstanceStatus>} value
 * @return {!proto.pando.api.survey.v1.SurveyInstancesStatusList} returns this
*/
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.setSurveyInstanceStatusList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.pando.api.survey.v1.SurveyInstanceStatus=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus}
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.addSurveyInstanceStatus = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.pando.api.survey.v1.SurveyInstanceStatus, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pando.api.survey.v1.SurveyInstancesStatusList} returns this
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.clearSurveyInstanceStatusList = function() {
  return this.setSurveyInstanceStatusList([]);
};


/**
 * repeated ChartData chart_data = 2;
 * @return {!Array<!proto.pando.api.survey.v1.ChartData>}
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.getChartDataList = function() {
  return /** @type{!Array<!proto.pando.api.survey.v1.ChartData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pando.api.survey.v1.ChartData, 2));
};


/**
 * @param {!Array<!proto.pando.api.survey.v1.ChartData>} value
 * @return {!proto.pando.api.survey.v1.SurveyInstancesStatusList} returns this
*/
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.setChartDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.pando.api.survey.v1.ChartData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pando.api.survey.v1.ChartData}
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.addChartData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.pando.api.survey.v1.ChartData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pando.api.survey.v1.SurveyInstancesStatusList} returns this
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.clearChartDataList = function() {
  return this.setChartDataList([]);
};


/**
 * optional pando.api.PaginationResult pagination = 100;
 * @return {?proto.pando.api.PaginationResult}
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.getPagination = function() {
  return /** @type{?proto.pando.api.PaginationResult} */ (
    jspb.Message.getWrapperField(this, pando_api_shared_pb.PaginationResult, 100));
};


/**
 * @param {?proto.pando.api.PaginationResult|undefined} value
 * @return {!proto.pando.api.survey.v1.SurveyInstancesStatusList} returns this
*/
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pando.api.survey.v1.SurveyInstancesStatusList} returns this
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pando.api.survey.v1.SurveyInstancesStatusList.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 100) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.survey.v1.SurveyInstanceStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.survey.v1.SurveyInstanceStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    guid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    organizationName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    dateCreated: (f = msg.getDateCreated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    contactInfo: jspb.Message.getFieldWithDefault(msg, 4, ""),
    respondentName: jspb.Message.getFieldWithDefault(msg, 5, ""),
    dateComplete: (f = msg.getDateComplete()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.survey.v1.SurveyInstanceStatus;
  return proto.pando.api.survey.v1.SurveyInstanceStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.survey.v1.SurveyInstanceStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrganizationName(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDateCreated(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setContactInfo(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRespondentName(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDateComplete(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.survey.v1.SurveyInstanceStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.survey.v1.SurveyInstanceStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrganizationName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDateCreated();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getContactInfo();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRespondentName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDateComplete();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string guid = 1;
 * @return {string}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.getGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus} returns this
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.setGuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string organization_name = 2;
 * @return {string}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.getOrganizationName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus} returns this
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.setOrganizationName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp date_created = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.getDateCreated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus} returns this
*/
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.setDateCreated = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus} returns this
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.clearDateCreated = function() {
  return this.setDateCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.hasDateCreated = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string contact_info = 4;
 * @return {string}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.getContactInfo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus} returns this
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.setContactInfo = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string respondent_name = 5;
 * @return {string}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.getRespondentName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus} returns this
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.setRespondentName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional google.protobuf.Timestamp date_complete = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.getDateComplete = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus} returns this
*/
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.setDateComplete = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus} returns this
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.clearDateComplete = function() {
  return this.setDateComplete(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.hasDateComplete = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string name = 7;
 * @return {string}
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.SurveyInstanceStatus} returns this
 */
proto.pando.api.survey.v1.SurveyInstanceStatus.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.survey.v1.ChartData.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.survey.v1.ChartData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.survey.v1.ChartData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.ChartData.toObject = function(includeInstance, msg) {
  var f, obj = {
    surveyName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    completeCount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    incompleteCount: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.survey.v1.ChartData}
 */
proto.pando.api.survey.v1.ChartData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.survey.v1.ChartData;
  return proto.pando.api.survey.v1.ChartData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.survey.v1.ChartData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.survey.v1.ChartData}
 */
proto.pando.api.survey.v1.ChartData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSurveyName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCompleteCount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIncompleteCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.survey.v1.ChartData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.survey.v1.ChartData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.survey.v1.ChartData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.survey.v1.ChartData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSurveyName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCompleteCount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getIncompleteCount();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string survey_name = 1;
 * @return {string}
 */
proto.pando.api.survey.v1.ChartData.prototype.getSurveyName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.survey.v1.ChartData} returns this
 */
proto.pando.api.survey.v1.ChartData.prototype.setSurveyName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 complete_count = 2;
 * @return {number}
 */
proto.pando.api.survey.v1.ChartData.prototype.getCompleteCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.pando.api.survey.v1.ChartData} returns this
 */
proto.pando.api.survey.v1.ChartData.prototype.setCompleteCount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 incomplete_count = 3;
 * @return {number}
 */
proto.pando.api.survey.v1.ChartData.prototype.getIncompleteCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pando.api.survey.v1.ChartData} returns this
 */
proto.pando.api.survey.v1.ChartData.prototype.setIncompleteCount = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


goog.object.extend(exports, proto.pando.api.survey.v1);
