// source: pando/api/extensions.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.object.extend(proto, google_protobuf_descriptor_pb);
goog.exportSymbol('proto.pando.api.ClaimMetadata', null, global);
goog.exportSymbol('proto.pando.api.MessageMetadata', null, global);
goog.exportSymbol('proto.pando.api.ScopeMetadata', null, global);
goog.exportSymbol('proto.pando.api.ServiceMetadata', null, global);
goog.exportSymbol('proto.pando.api.field', null, global);
goog.exportSymbol('proto.pando.api.message', null, global);
goog.exportSymbol('proto.pando.api.method', null, global);
goog.exportSymbol('proto.pando.api.oneof', null, global);
goog.exportSymbol('proto.pando.api.service', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.ServiceMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pando.api.ServiceMetadata.repeatedFields_, null);
};
goog.inherits(proto.pando.api.ServiceMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.ServiceMetadata.displayName = 'proto.pando.api.ServiceMetadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.MessageMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pando.api.MessageMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.MessageMetadata.displayName = 'proto.pando.api.MessageMetadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.ScopeMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pando.api.ScopeMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.ScopeMetadata.displayName = 'proto.pando.api.ScopeMetadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.ClaimMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pando.api.ClaimMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.ClaimMetadata.displayName = 'proto.pando.api.ClaimMetadata';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pando.api.ServiceMetadata.repeatedFields_ = [1,2,5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.ServiceMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.ServiceMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.ServiceMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.ServiceMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    requiredScopeList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    requiredClaimList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    requireUserAuth: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    requireClientAuth: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    optionalScopeList: jspb.Message.toObjectList(msg.getOptionalScopeList(),
    proto.pando.api.ScopeMetadata.toObject, includeInstance),
    optionalClaimList: jspb.Message.toObjectList(msg.getOptionalClaimList(),
    proto.pando.api.ClaimMetadata.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.ServiceMetadata}
 */
proto.pando.api.ServiceMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.ServiceMetadata;
  return proto.pando.api.ServiceMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.ServiceMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.ServiceMetadata}
 */
proto.pando.api.ServiceMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addRequiredScope(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addRequiredClaim(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRequireUserAuth(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRequireClientAuth(value);
      break;
    case 5:
      var value = new proto.pando.api.ScopeMetadata;
      reader.readMessage(value,proto.pando.api.ScopeMetadata.deserializeBinaryFromReader);
      msg.addOptionalScope(value);
      break;
    case 6:
      var value = new proto.pando.api.ClaimMetadata;
      reader.readMessage(value,proto.pando.api.ClaimMetadata.deserializeBinaryFromReader);
      msg.addOptionalClaim(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.ServiceMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.ServiceMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.ServiceMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.ServiceMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequiredScopeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getRequiredClaimList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getRequireUserAuth();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getRequireClientAuth();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getOptionalScopeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.pando.api.ScopeMetadata.serializeBinaryToWriter
    );
  }
  f = message.getOptionalClaimList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.pando.api.ClaimMetadata.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string required_scope = 1;
 * @return {!Array<string>}
 */
proto.pando.api.ServiceMetadata.prototype.getRequiredScopeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pando.api.ServiceMetadata} returns this
 */
proto.pando.api.ServiceMetadata.prototype.setRequiredScopeList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pando.api.ServiceMetadata} returns this
 */
proto.pando.api.ServiceMetadata.prototype.addRequiredScope = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pando.api.ServiceMetadata} returns this
 */
proto.pando.api.ServiceMetadata.prototype.clearRequiredScopeList = function() {
  return this.setRequiredScopeList([]);
};


/**
 * repeated string required_claim = 2;
 * @return {!Array<string>}
 */
proto.pando.api.ServiceMetadata.prototype.getRequiredClaimList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pando.api.ServiceMetadata} returns this
 */
proto.pando.api.ServiceMetadata.prototype.setRequiredClaimList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pando.api.ServiceMetadata} returns this
 */
proto.pando.api.ServiceMetadata.prototype.addRequiredClaim = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pando.api.ServiceMetadata} returns this
 */
proto.pando.api.ServiceMetadata.prototype.clearRequiredClaimList = function() {
  return this.setRequiredClaimList([]);
};


/**
 * optional bool require_user_auth = 3;
 * @return {boolean}
 */
proto.pando.api.ServiceMetadata.prototype.getRequireUserAuth = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pando.api.ServiceMetadata} returns this
 */
proto.pando.api.ServiceMetadata.prototype.setRequireUserAuth = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool require_client_auth = 4;
 * @return {boolean}
 */
proto.pando.api.ServiceMetadata.prototype.getRequireClientAuth = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pando.api.ServiceMetadata} returns this
 */
proto.pando.api.ServiceMetadata.prototype.setRequireClientAuth = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * repeated ScopeMetadata optional_scope = 5;
 * @return {!Array<!proto.pando.api.ScopeMetadata>}
 */
proto.pando.api.ServiceMetadata.prototype.getOptionalScopeList = function() {
  return /** @type{!Array<!proto.pando.api.ScopeMetadata>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pando.api.ScopeMetadata, 5));
};


/**
 * @param {!Array<!proto.pando.api.ScopeMetadata>} value
 * @return {!proto.pando.api.ServiceMetadata} returns this
*/
proto.pando.api.ServiceMetadata.prototype.setOptionalScopeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.pando.api.ScopeMetadata=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pando.api.ScopeMetadata}
 */
proto.pando.api.ServiceMetadata.prototype.addOptionalScope = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.pando.api.ScopeMetadata, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pando.api.ServiceMetadata} returns this
 */
proto.pando.api.ServiceMetadata.prototype.clearOptionalScopeList = function() {
  return this.setOptionalScopeList([]);
};


/**
 * repeated ClaimMetadata optional_claim = 6;
 * @return {!Array<!proto.pando.api.ClaimMetadata>}
 */
proto.pando.api.ServiceMetadata.prototype.getOptionalClaimList = function() {
  return /** @type{!Array<!proto.pando.api.ClaimMetadata>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pando.api.ClaimMetadata, 6));
};


/**
 * @param {!Array<!proto.pando.api.ClaimMetadata>} value
 * @return {!proto.pando.api.ServiceMetadata} returns this
*/
proto.pando.api.ServiceMetadata.prototype.setOptionalClaimList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.pando.api.ClaimMetadata=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pando.api.ClaimMetadata}
 */
proto.pando.api.ServiceMetadata.prototype.addOptionalClaim = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.pando.api.ClaimMetadata, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pando.api.ServiceMetadata} returns this
 */
proto.pando.api.ServiceMetadata.prototype.clearOptionalClaimList = function() {
  return this.setOptionalClaimList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.MessageMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.MessageMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.MessageMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.MessageMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    personalInfo: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    sensitiveInfo: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    responseOnly: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    requestOnly: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    requestRequired: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.MessageMetadata}
 */
proto.pando.api.MessageMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.MessageMetadata;
  return proto.pando.api.MessageMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.MessageMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.MessageMetadata}
 */
proto.pando.api.MessageMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPersonalInfo(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSensitiveInfo(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setResponseOnly(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRequestOnly(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRequestRequired(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.MessageMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.MessageMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.MessageMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.MessageMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPersonalInfo();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getSensitiveInfo();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getResponseOnly();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getRequestOnly();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getRequestRequired();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional bool personal_info = 1;
 * @return {boolean}
 */
proto.pando.api.MessageMetadata.prototype.getPersonalInfo = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pando.api.MessageMetadata} returns this
 */
proto.pando.api.MessageMetadata.prototype.setPersonalInfo = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool sensitive_info = 2;
 * @return {boolean}
 */
proto.pando.api.MessageMetadata.prototype.getSensitiveInfo = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pando.api.MessageMetadata} returns this
 */
proto.pando.api.MessageMetadata.prototype.setSensitiveInfo = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool response_only = 3;
 * @return {boolean}
 */
proto.pando.api.MessageMetadata.prototype.getResponseOnly = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pando.api.MessageMetadata} returns this
 */
proto.pando.api.MessageMetadata.prototype.setResponseOnly = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool request_only = 4;
 * @return {boolean}
 */
proto.pando.api.MessageMetadata.prototype.getRequestOnly = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pando.api.MessageMetadata} returns this
 */
proto.pando.api.MessageMetadata.prototype.setRequestOnly = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool request_required = 5;
 * @return {boolean}
 */
proto.pando.api.MessageMetadata.prototype.getRequestRequired = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pando.api.MessageMetadata} returns this
 */
proto.pando.api.MessageMetadata.prototype.setRequestRequired = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.ScopeMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.ScopeMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.ScopeMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.ScopeMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    scope: jspb.Message.getFieldWithDefault(msg, 1, ""),
    note: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.ScopeMetadata}
 */
proto.pando.api.ScopeMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.ScopeMetadata;
  return proto.pando.api.ScopeMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.ScopeMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.ScopeMetadata}
 */
proto.pando.api.ScopeMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setScope(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.ScopeMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.ScopeMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.ScopeMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.ScopeMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScope();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNote();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string scope = 1;
 * @return {string}
 */
proto.pando.api.ScopeMetadata.prototype.getScope = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.ScopeMetadata} returns this
 */
proto.pando.api.ScopeMetadata.prototype.setScope = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string note = 2;
 * @return {string}
 */
proto.pando.api.ScopeMetadata.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.ScopeMetadata} returns this
 */
proto.pando.api.ScopeMetadata.prototype.setNote = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.ClaimMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.ClaimMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.ClaimMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.ClaimMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    claim: jspb.Message.getFieldWithDefault(msg, 1, ""),
    note: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.ClaimMetadata}
 */
proto.pando.api.ClaimMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.ClaimMetadata;
  return proto.pando.api.ClaimMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.ClaimMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.ClaimMetadata}
 */
proto.pando.api.ClaimMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClaim(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.ClaimMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.ClaimMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.ClaimMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.ClaimMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClaim();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNote();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string claim = 1;
 * @return {string}
 */
proto.pando.api.ClaimMetadata.prototype.getClaim = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.ClaimMetadata} returns this
 */
proto.pando.api.ClaimMetadata.prototype.setClaim = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string note = 2;
 * @return {string}
 */
proto.pando.api.ClaimMetadata.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.ClaimMetadata} returns this
 */
proto.pando.api.ClaimMetadata.prototype.setNote = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `service`.
 * @type {!jspb.ExtensionFieldInfo<!proto.pando.api.ServiceMetadata>}
 */
proto.pando.api.service = new jspb.ExtensionFieldInfo(
    84057,
    {service: 0},
    proto.pando.api.ServiceMetadata,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.pando.api.ServiceMetadata.toObject),
    0);

google_protobuf_descriptor_pb.ServiceOptions.extensionsBinary[84057] = new jspb.ExtensionFieldBinaryInfo(
    proto.pando.api.service,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.pando.api.ServiceMetadata.serializeBinaryToWriter,
    proto.pando.api.ServiceMetadata.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.ServiceOptions.extensions[84057] = proto.pando.api.service;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `method`.
 * @type {!jspb.ExtensionFieldInfo<!proto.pando.api.ServiceMetadata>}
 */
proto.pando.api.method = new jspb.ExtensionFieldInfo(
    84057,
    {method: 0},
    proto.pando.api.ServiceMetadata,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.pando.api.ServiceMetadata.toObject),
    0);

google_protobuf_descriptor_pb.MethodOptions.extensionsBinary[84057] = new jspb.ExtensionFieldBinaryInfo(
    proto.pando.api.method,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.pando.api.ServiceMetadata.serializeBinaryToWriter,
    proto.pando.api.ServiceMetadata.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MethodOptions.extensions[84057] = proto.pando.api.method;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `message`.
 * @type {!jspb.ExtensionFieldInfo<!proto.pando.api.MessageMetadata>}
 */
proto.pando.api.message = new jspb.ExtensionFieldInfo(
    84057,
    {message: 0},
    proto.pando.api.MessageMetadata,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.pando.api.MessageMetadata.toObject),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[84057] = new jspb.ExtensionFieldBinaryInfo(
    proto.pando.api.message,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.pando.api.MessageMetadata.serializeBinaryToWriter,
    proto.pando.api.MessageMetadata.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[84057] = proto.pando.api.message;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `field`.
 * @type {!jspb.ExtensionFieldInfo<!proto.pando.api.MessageMetadata>}
 */
proto.pando.api.field = new jspb.ExtensionFieldInfo(
    84057,
    {field: 0},
    proto.pando.api.MessageMetadata,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.pando.api.MessageMetadata.toObject),
    0);

google_protobuf_descriptor_pb.FieldOptions.extensionsBinary[84057] = new jspb.ExtensionFieldBinaryInfo(
    proto.pando.api.field,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.pando.api.MessageMetadata.serializeBinaryToWriter,
    proto.pando.api.MessageMetadata.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FieldOptions.extensions[84057] = proto.pando.api.field;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `oneof`.
 * @type {!jspb.ExtensionFieldInfo<!proto.pando.api.MessageMetadata>}
 */
proto.pando.api.oneof = new jspb.ExtensionFieldInfo(
    84057,
    {oneof: 0},
    proto.pando.api.MessageMetadata,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.pando.api.MessageMetadata.toObject),
    0);

google_protobuf_descriptor_pb.OneofOptions.extensionsBinary[84057] = new jspb.ExtensionFieldBinaryInfo(
    proto.pando.api.oneof,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.pando.api.MessageMetadata.serializeBinaryToWriter,
    proto.pando.api.MessageMetadata.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.OneofOptions.extensions[84057] = proto.pando.api.oneof;

goog.object.extend(exports, proto.pando.api);
