export const ApplicationConfigTypes = {
  GET_APPLICATION_CONFIG_START: "GET_APPLICATION_CONFIG_START",
  FETCHING_APPLICATION_CONFIG: "FETCHING_APPLICATION_CONFIG",
  GET_APPLICATION_SUCCESS: "GET_APPLICATION_CONFIG_SUCCESS",
  GET_APPLICATION_CONFIG_FAILURE: "GET_APPLICATION_CONFIG_FAILURE",
};
