interface IAuthTypes {
  CHECK_AUTH_START: "CHECK_AUTH_START";
  CHECK_AUTH_SUCCESS: "CHECK_AUTH_SUCCESS";
  CHECK_AUTH_FAILURE: "CHECK_AUTH_FAILURE";
  UNAUTHORIZED_USER: "UNAUTHORIZED_USER";
}

export type checkAuthSuccessType = {
  isAuthorize: boolean;
};

export const AuthTypes: IAuthTypes = {
  CHECK_AUTH_START: "CHECK_AUTH_START",
  CHECK_AUTH_SUCCESS: "CHECK_AUTH_SUCCESS",
  CHECK_AUTH_FAILURE: "CHECK_AUTH_FAILURE",
  UNAUTHORIZED_USER: "UNAUTHORIZED_USER",
};

export const LoginTypes = {
  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_IS_FETCHING: "LOGIN_IS_FETCHING",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  LOGIN_POST_TOKEN_TO_DB: "LOGIN_POST_TOKEN_TO_DB",
};

export const LiveSearch = {
  SEARCH: "LIVE_SEARCH",
};
