export const InitializeGRPCclientTypes = {
  INTIALIZE_GRPC_CLIENT_START: "INTIALIZE_GRPC_CLIENT_START",
  INTIALIZE_GRPC_CLIENT_SUCCESS: "INTIALIZE_GRPC_CLIENT_SUCCESS",
};

export const SurveyTypes = {
  GET_SURVEYS_START: "GET_SURVEYS_START",
  GET_SURVEYS_SUCCESS: "GET_SURVEYS_SUCCESS",
  GET_SURVEYS_FAILURE: "GET_SURVEYS_FAILURE",
};
