import { call, takeLatest, put } from "redux-saga/effects";

import { InitializeGRPCclientTypes } from "./types";
import { InitializeGRPCclientSuccess } from "./actions";
import { grpcClient } from "./api";
import { response } from "express";

const TOKEN =
  "eyJhbGciOiJSUzI1NiIsImtpZCI6IkI2NzFDNjEwNjlFNEQ1QTU0MzNGNTQ2QkQwRDVBRTE1MzlCMTYxMzgiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJ0bkhHRUduazFhVkRQMVJyME5XdUZUbXhZVGcifQ.eyJuYmYiOjE2NDMzNDk0NjMsImV4cCI6MTY0MzM1MzA2MywiaXNzIjoiaHR0cHM6Ly9sb2dpbi5zdGFnaW5nLnBhbmRvbGluay5jb20iLCJhdWQiOlsiY2FudmFzc2luZ19zZXJ2aWNlIiwiY29tbXVuaWNhdGlvbl9zZXJ2aWNlIiwiY29udGFjdF9zZXJ2aWNlIiwiZXNpZ25fc2VydmljZSIsIklkZW50aXR5U2VydmVyQXBpIiwicGFuZG9fYXBwX3NlcnZpY2UiLCJ2YXVsdF9zZXJ2aWNlIiwic3VydmV5X3NlcnZpY2UiLCJ0ZW1wbGF0ZV9zZXJ2aWNlIl0sImNsaWVudF9pZCI6IjgxQ0Q4NjAyLTNCMTYtNEFENi04MUVDLTg5RDZCOTQ2NUY4MCIsImFjY2Vzc19jb2RlIjoiUFVCTElDLUFQSSIsInZhdWx0X3NlcnZpY2U6Y3VzdG9tZXJfaW5mbyI6WyJhbGxpYW5jZTpyZWFkIiwiYWxsaWFuY2U6d3JpdGUiLCJhbGxpYW5jZTpkZWxldGUiXSwicGVyc29uYWxfaW5mbyI6WyJhbGxpYW5jZTpyZWFkIiwiYWxsaWFuY2U6d3JpdGUiLCJ0ZXN0OnJlYWQiLCJhbGxpYW5jZTpkZWxldGUiLCJkZW1vOndyaXRlIl0sImVzaWduIjpbImFsbGlhbmNlOnJlYWQiLCJhbGxpYW5jZTp3cml0ZSJdLCJlc2lnbjpjbGFpbXNfbWFuYWdlbWVudCI6ImFsbGlhbmNlIiwidGVtcGxhdGUiOlsiYWxsaWFuY2U6cmVhZCIsImFsbGlhbmNlOndyaXRlIiwiYWxkZXI6cmVhZCIsImFsZGVyOmRlbGV0ZSIsImFsZGVyOndyaXRlIiwidGVzdDpyZWFkIiwidGVzdDp3cml0ZSIsInRlc3Q6ZGVsZXRlIiwiZGVtbzp3cml0ZSIsImRlbW86cmVhZCIsImFsbGlhbmNlOmRlbGV0ZSJdLCJlc2lnbjpzaWduYXRvcnkiOlsidGVzdDpyZWFkIiwiYWxsaWFuY2U6cmVhZCJdLCJlc2lnbjpyZXF1ZXN0IjpbImFsbGlhbmNlOndyaXRlIiwiYWxsaWFuY2U6cmVhZCIsImRlbW86d3JpdGUiLCJkZW1vOnJlYWQiXSwiZXNpZ246dGVtcGxhdGUiOlsiYWxsaWFuY2U6d3JpdGUiLCJhbGxpYW5jZTpyZWFkIiwiZGVtbzp3cml0ZSIsImRlbW86cmVhZCIsImFsbGlhbmNlOmRlbGV0ZSJdLCJzdXJ2ZXk6aW5zdGFuY2UiOlsiYWxsaWFuY2U6cmVhZCIsImFsbGlhbmNlOndyaXRlIl0sInN1cnZleTp0ZW1wbGF0ZSI6WyJhbGxpYW5jZTpyZWFkIiwiYWxsaWFuY2U6d3JpdGUiLCJkZW1vOndyaXRlIiwiZGVtbzpyZWFkIl0sInN1cnZleTpyZXBvcnRzIjoiYWxsaWFuY2U6aW5zdGFuY2VzIiwic3VydmV5OnJlcXVlc3QiOlsiYWxsaWFuY2U6d3JpdGUiLCJkZW1vOndyaXRlIiwiZGVtbzpyZWFkIl0sInNjb3BlIjpbImNhbnZhc3NpbmciLCJjb21tdW5pY2F0aW9uIiwiY29udGFjdCIsImVzaWduIiwiZXNpZ246YWRtaW4iLCJJZGVudGl0eVNlcnZlckFwaSIsInBhbmRvX2FwcCIsInBlcnNvbmFsX2luZm8iLCJ2YXVsdF9zZXJ2aWNlIiwic3VydmV5Iiwic3VydmV5OmFkbWluIiwic3VydmV5OnJlcG9ydHMiLCJ0ZW1wbGF0ZSIsInRlbXBsYXRlOmFkbWluIl19.B4vtu_mkuhDAGSNHa0clyceVreXEOQ__l3r2eXq7UG3gd8a5cQ4BmGoEPKuaygxOwxaIjyJ7rV8i6bRKuIqwawA8fChnR6HWWogssPW_-Q0BRxvtk5Ql3dsM7_aBMJ38Dztr0xP_N1jxBZUEqmsYUJkbNfIQFtVwwqP-UrzsyNV9mAV7QtmlXBZ4IWu0YWHjHnsYbmc9hvTq5HF7zNzLFgcGS0dmn0gfmYjBYqJWj8NWhZTrExf2jfCo6MEn-9IdIycE5iGtQR8RGLfKYwEOlCGxO8F-1rICxhq0tfsC4lZZgkJfH8AVL8ewHEuQbp9uYAuLxPl72sDOHltnaEyNXg";

const grpcClientConnectionAsync = function* () {
  try {
    const client = yield grpcClient(TOKEN, (result) => {});
    yield client && put(InitializeGRPCclientSuccess(client));
  } catch (e) {}
};

const grpcClientConnectionStart = function* () {
  yield takeLatest(
    InitializeGRPCclientTypes.INTIALIZE_GRPC_CLIENT_START,
    grpcClientConnectionAsync
  );
};

export const grpcClientConnectionSaga = function* () {
  yield call(grpcClientConnectionStart);
};
